# I. NumPy.

**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

0. Імпортувати numpy загальноприйнятим способом.

In [1]:
import numpy as np

1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [3]:
grades = [1, 2, 3, 4, 5]

grades_np = np.array(grades)

2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [4]:
prices = [[1, 2, 3, 4, 5],
          [6, 7, 8, 9, 10],
          [11, 12, 13, 14, 15],
          [16, 17, 18, 19, 20]]

prices_np = np.array(prices)

3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [5]:
print(grades_np.dtype)
print(prices_np.dtype)

int64
int64


4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [ ]:
print(grades_np.shape)
print(prices_np.shape)

5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [8]:
profit = np.linspace(0, 1000.5, 7)

print(profit)

[   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]


6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [13]:
arr1 = np.linspace(0, 1000.5, 7)
arr2 = np.linspace(0, 1000.5, 7)

vertical_arr = np.vstack((arr1, arr2))
horizontal_arr = np.hstack((arr1, arr2))

print(vertical_arr)
print(horizontal_arr)


[[   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]
 [   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]]
[   0.    166.75  333.5   500.25  667.    833.75 1000.5     0.    166.75
  333.5   500.25  667.    833.75 1000.5 ]


7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [17]:
arr1 = [1, 2, 3, 4, 5]
arr2 = [1, 2, 3, 4, 5]

add_result = np.add(arr1, arr2)
subtract_result = np.subtract(arr1, arr2)
multiply_result = np.multiply(arr1, arr2)
multiply_scalar_result = np.multiply(arr1, 3)


print(add_result)
print(subtract_result)
print(multiply_result)
print(multiply_scalar_result)


[ 2  4  6  8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]
[ 3  6  9 12 15]


9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [18]:
prices = [[1, 2, 3, 4, 5],
          [6, 7, 8, 9, 10],
          [11, 12, 13, 14, 15],
          [16, 17, 18, 19, 20]]

prices_np = np.array(prices)

min_value = np.min(prices_np)
max_value = np.max(prices_np)
sum_value = np.sum(prices_np)
min_row_values = np.min(prices_np, axis=1)
max_column_values = np.max(prices_np, axis=0)


print(min_value)
print(max_value)
print(sum_value)
print(min_row_values)
print(max_column_values)

1
20
210
[ 1  6 11 16]
[16 17 18 19 20]


10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [23]:
matrix = [[1, 2, 3, 4, 5],
          [6, 1, 8, 9, 10],
          [11, 12, 1, 14, 15],
          [16, 5, 18, 19, 2]]

unique_values = np.unique(matrix)
counts = np.unique(matrix, return_counts=True)

print(unique_values)
print(counts)

[ 1  2  3  4  5  6  8  9 10 11 12 14 15 16 18 19]
(array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 14, 15, 16, 18, 19]), array([3, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))


# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas

In [3]:
import pandas as pd

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [ ]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Lisa', ''],
    'Surname': ['Doe', 'Smith', 'Johnson', 'Williams', 'Brown'],
    'Birthdate': ['1990-05-15', '1985-12-03', '1988-01-22', '1992-07-18', ''],
    'Weight': [75, 68, 82, 70, ''],
    'Medical_insurance': [True, False, True, True, False]
}

df = pd.DataFrame(data)

# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [7]:
df = pd.read_csv('missile_attacks_daily.csv')

# IV. Data understanding

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

In [5]:
df.head(10)

time_start          time_end             model  \
0  2025-01-18 20:00  2025-01-19 09:00    Shahed-136/131   
1  2025-01-17 19:00  2025-01-18 08:00    Shahed-136/131   
2  2025-01-16 19:00  2025-01-17 09:00    Shahed-136/131   
3  2025-01-16 19:00  2025-01-17 09:00  Iskander-M/KN-23   
4  2025-01-16 19:00  2025-01-17 09:00        Iskander-M   
5  2025-01-15 20:00  2025-01-16 09:00    Shahed-136/131   
6  2025-01-15 06:00  2025-01-15 08:00         X-59/X-69   
7  2025-01-15 06:00  2025-01-15 08:00         X-22/X-32   
8  2025-01-15 06:00  2025-01-15 08:00       X-101/X-555   
9  2025-01-15 06:00  2025-01-15 08:00            Kalibr   

                                        launch_place       target  carrier  \
0      Bryansk oblast and Oryol oblast and Millerovo      Ukraine      NaN   
1  Primorsko-Akhtarsk and Bryansk oblast and Mill...      Ukraine      NaN   
2  Primorsko-Akhtarsk and Kursk oblast and Bryans...      Ukraine      NaN   
3                 Bryansk oblast and Voronezh oblast  Kyiv oblast      NaN   
4                                      Rostov oblast      Ukraine      NaN   
5  Primorsko-Akhtarsk and Bryansk oblast and Oryo...      Ukraine      NaN   
6                                    Belgorod oblast      Ukraine      NaN   
7                                        Tula oblast      Ukraine  Tu-22M3   
8                                   Volgograd oblast      Ukraine  Tu-95MS   
9                                          Black Sea      Ukraine     Navi   

   launched  destroyed  not_reach_goal  cross_border_belarus  back_russia  \
0      61.0         43            15.0                   NaN          NaN   
1      39.0         24            14.0                   NaN          NaN   
2      50.0         33             9.0                   NaN          NaN   
3       4.0          2             NaN                   NaN          NaN   
4       2.0          0             NaN                   NaN          NaN   
5      55.0         34            18.0                   NaN          NaN   
6       4.0          4             NaN                   NaN          NaN   
7       7.0          0             NaN                   NaN          NaN   
8      27.0         23             NaN                   NaN          NaN   
9       4.0          3             NaN                   NaN          NaN   

   still_attacking                                  destroyed_details  \
0              1.0  {'Mykolaiv oblast': NaN,    'Kyiv oblast': NaN...   
1              NaN  {'Kherson oblast': NaN, 'Khmelnytskyi oblast':...   
2              NaN  {'Odesa oblast and Mykolaiv oblast': 7, 'Khmel...   
3              NaN                                                NaN   
4              NaN                                                NaN   
5              NaN  {'Mykolaiv oblast': 5, 'Kyiv oblast': NaN, 'Su...   
6              NaN                                                NaN   
7              NaN                                                NaN   
8              NaN                                       {'west': 20}   
9              NaN                                       {'south': 1}   

  launched_details launch_place_details  \
0              NaN                  NaN   
1              NaN                  NaN   
2              NaN                  NaN   
3              NaN                  NaN   
4              NaN                  NaN   
5              NaN                  NaN   
6              NaN                  NaN   
7              NaN                  NaN   
8              NaN                  NaN   
9              NaN                  NaN   

                                              source  
0  kpszsu/posts/pfbid0meYNAsX4voALE4SXunVpzKTwzrJ...  
1  kpszsu/posts/pfbid0Rpzfu7u9ERu4o49Gm12eqSogKvZ...  
2  kpszsu/posts/pfbid0Gvye9Wn2gj8RPiiGaTQFGRas9Yg...  
3  kpszsu/posts/pfbid0Rpzfu7u9ERu4o49Gm12eqSogKvZ...  
4  kpszsu/posts/pfbid0Gvye9Wn2gj8RPiiGaTQFGRas9Yg...  
5  kpszsu/posts/pfbid0tPwzQHvvr63PbehDshED2W

14. Отримайте інформацію про форму датафрейму.

In [8]:
print(df.shape)

(2044, 16)


15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

In [10]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2044 entries, 0 to 2043
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   time_start            2044 non-null   object 
 1   time_end              2044 non-null   object 
 2   model                 2044 non-null   object 
 3   launch_place          1023 non-null   object 
 4   target                2016 non-null   object 
 5   carrier               225 non-null    object 
 6   launched              2041 non-null   float64
 7   destroyed             2044 non-null   int64  
 8   not_reach_goal        157 non-null    float64
 9   cross_border_belarus  32 non-null     float64
 10  back_russia           34 non-null     float64
 11  still_attacking       28 non-null     float64
 12  destroyed_details     294 non-null    object 
 13  launched_details      4 non-null      object 
 14  launch_place_details  4 non-null      object 
 15  source               

16. Отримайте статистику для колонок числового типу.

In [11]:
print(df.describe())

          launched    destroyed  not_reach_goal  cross_border_belarus  \
count  2041.000000  2044.000000      157.000000             32.000000   
mean     10.609995     7.491683       20.828025              2.312500   
std      21.041038    14.190972       19.877245              2.054696   
min       1.000000     0.000000        1.000000              1.000000   
25%       1.000000     1.000000        4.000000              1.000000   
50%       2.000000     1.000000       16.000000              2.000000   
75%       9.000000     7.000000       30.000000              2.000000   
max     193.000000    99.000000      105.000000             10.000000   

       back_russia  still_attacking  
count    34.000000        28.000000  
mean      2.000000         2.821429  
std       1.154701         2.931989  
min       1.000000         1.000000  
25%       1.000000         1.000000  
50%       2.000000         1.000000  
75%       3.000000         4.000000  
max       5.000000        10.000000  


17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

In [12]:
print(df.nunique())

time_start               864
time_end                1015
model                     61
launch_place             135
target                    97
carrier                   58
launched                 113
destroyed                 81
not_reach_goal            55
cross_border_belarus       7
back_russia                5
still_attacking            8
destroyed_details        290
launched_details           4
launch_place_details       4
source                   960
dtype: int64


In [ ]:
# Виправити порожні дані (очистити чи заповнити)
# Позбавитись від повторюваних значень

18. На основі отриманої інформації про датасет вище, опишіть по пунктах, що б ви виправили або на що б звернули увагу на кроці очищення даних і чому?

**місце для текстової відповіді**

1.   Пункт списку
2.   Пункт списку

...


# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

In [14]:
df['launched'] = df['launched'].astype('Int64')

20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

In [18]:
df_cleaned = df.dropna(thresh=len(df)*0.3, axis=1)
df_cleaned.head(10)

time_start          time_end             model  \
0  2025-01-18 20:00  2025-01-19 09:00    Shahed-136/131   
1  2025-01-17 19:00  2025-01-18 08:00    Shahed-136/131   
2  2025-01-16 19:00  2025-01-17 09:00    Shahed-136/131   
3  2025-01-16 19:00  2025-01-17 09:00  Iskander-M/KN-23   
4  2025-01-16 19:00  2025-01-17 09:00        Iskander-M   
5  2025-01-15 20:00  2025-01-16 09:00    Shahed-136/131   
6  2025-01-15 06:00  2025-01-15 08:00         X-59/X-69   
7  2025-01-15 06:00  2025-01-15 08:00         X-22/X-32   
8  2025-01-15 06:00  2025-01-15 08:00       X-101/X-555   
9  2025-01-15 06:00  2025-01-15 08:00            Kalibr   

                                        launch_place       target  launched  \
0      Bryansk oblast and Oryol oblast and Millerovo      Ukraine        61   
1  Primorsko-Akhtarsk and Bryansk oblast and Mill...      Ukraine        39   
2  Primorsko-Akhtarsk and Kursk oblast and Bryans...      Ukraine        50   
3                 Bryansk oblast and Voronezh oblast  Kyiv oblast         4   
4                                      Rostov oblast      Ukraine         2   
5  Primorsko-Akhtarsk and Bryansk oblast and Oryo...      Ukraine        55   
6                                    Belgorod oblast      Ukraine         4   
7                                        Tula oblast      Ukraine         7   
8                                   Volgograd oblast      Ukraine        27   
9                                          Black Sea      Ukraine         4   

   destroyed                                             source  
0         43  kpszsu/posts/pfbid0meYNAsX4voALE4SXunVpzKTwzrJ...  
1         24  kpszsu/posts/pfbid0Rpzfu7u9ERu4o49Gm12eqSogKvZ...  
2         33  kpszsu/posts/pfbid0Gvye9Wn2gj8RPiiGaTQFGRas9Yg...  
3          2  kpszsu/posts/pfbid0Rpzfu7u9ERu4o49Gm12eqSogKvZ...  
4          0  kpszsu/posts/pfbid0Gvye9Wn2gj8RPiiGaTQFGRas9Yg...  
5         34  kpszsu/posts/pfbid0tPwzQHvvr63PbehDshED2WNV2vm...  
6          4  kpszsu/posts/pfbid0kLxxfDQRTeUt5wQT5eahJVkW1fb...  
7          0  kpszsu/posts/pfbid0kLxxfDQRTeUt5wQT5eahJVkW1fb...  
8         23  kpszsu/posts/pfbid0kLxxfDQRTeUt5wQT5eahJVkW1fb...  
9          3  kpszsu/posts/pfbid0kLxxfDQRTeUt5wQT5eahJVkW1fb...

21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

In [19]:
df_cleaned = df.drop_duplicates()
df_cleaned.head(10)

time_start          time_end             model  \
0  2025-01-18 20:00  2025-01-19 09:00    Shahed-136/131   
1  2025-01-17 19:00  2025-01-18 08:00    Shahed-136/131   
2  2025-01-16 19:00  2025-01-17 09:00    Shahed-136/131   
3  2025-01-16 19:00  2025-01-17 09:00  Iskander-M/KN-23   
4  2025-01-16 19:00  2025-01-17 09:00        Iskander-M   
5  2025-01-15 20:00  2025-01-16 09:00    Shahed-136/131   
6  2025-01-15 06:00  2025-01-15 08:00         X-59/X-69   
7  2025-01-15 06:00  2025-01-15 08:00         X-22/X-32   
8  2025-01-15 06:00  2025-01-15 08:00       X-101/X-555   
9  2025-01-15 06:00  2025-01-15 08:00            Kalibr   

                                        launch_place       target  carrier  \
0      Bryansk oblast and Oryol oblast and Millerovo      Ukraine      NaN   
1  Primorsko-Akhtarsk and Bryansk oblast and Mill...      Ukraine      NaN   
2  Primorsko-Akhtarsk and Kursk oblast and Bryans...      Ukraine      NaN   
3                 Bryansk oblast and Voronezh oblast  Kyiv oblast      NaN   
4                                      Rostov oblast      Ukraine      NaN   
5  Primorsko-Akhtarsk and Bryansk oblast and Oryo...      Ukraine      NaN   
6                                    Belgorod oblast      Ukraine      NaN   
7                                        Tula oblast      Ukraine  Tu-22M3   
8                                   Volgograd oblast      Ukraine  Tu-95MS   
9                                          Black Sea      Ukraine     Navi   

   launched  destroyed  not_reach_goal  cross_border_belarus  back_russia  \
0        61         43            15.0                   NaN          NaN   
1        39         24            14.0                   NaN          NaN   
2        50         33             9.0                   NaN          NaN   
3         4          2             NaN                   NaN          NaN   
4         2          0             NaN                   NaN          NaN   
5        55         34            18.0                   NaN          NaN   
6         4          4             NaN                   NaN          NaN   
7         7          0             NaN                   NaN          NaN   
8        27         23             NaN                   NaN          NaN   
9         4          3             NaN                   NaN          NaN   

   still_attacking                                  destroyed_details  \
0              1.0  {'Mykolaiv oblast': NaN,    'Kyiv oblast': NaN...   
1              NaN  {'Kherson oblast': NaN, 'Khmelnytskyi oblast':...   
2              NaN  {'Odesa oblast and Mykolaiv oblast': 7, 'Khmel...   
3              NaN                                                NaN   
4              NaN                                                NaN   
5              NaN  {'Mykolaiv oblast': 5, 'Kyiv oblast': NaN, 'Su...   
6              NaN                                                NaN   
7              NaN                                                NaN   
8              NaN                                       {'west': 20}   
9              NaN                                       {'south': 1}   

  launched_details launch_place_details  \
0              NaN                  NaN   
1              NaN                  NaN   
2              NaN                  NaN   
3              NaN                  NaN   
4              NaN                  NaN   
5              NaN                  NaN   
6              NaN                  NaN   
7              NaN                  NaN   
8              NaN                  NaN   
9              NaN                  NaN   

                                              source  
0  kpszsu/posts/pfbid0meYNAsX4voALE4SXunVpzKTwzrJ...  
1  kpszsu/posts/pfbid0Rpzfu7u9ERu4o49Gm12eqSogKvZ...  
2  kpszsu/posts/pfbid0Gvye9Wn2gj8RPiiGaTQFGRas9Yg...  
3  kpszsu/posts/pfbid0Rpzfu7u9ERu4o49Gm12eqSogKvZ...  
4  kpszsu/posts/pfbid0Gvye9Wn2gj8RPiiGaTQFGRas9Yg...  
5  kpszsu/posts/pfbid0tPwzQHvvr63PbehDshED2W

**місце для текстової відповіді**

22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.

In [20]:
print([df.isnull().any(axis=1)])

[0       True
1       True
2       True
3       True
4       True
        ... 
2039    True
2040    True
2041    True
2042    True
2043    True
Length: 2044, dtype: bool]
